version: "3.8"
name: "Acceso a la base de datos"
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT:-8000}:8080
    environment:
      ADMINER_DEFAULT_SERVER: 'myappcloud.net'